# Generated by Django 4.1.5 on 2023-07-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(verbose_name='评论来源标识')),
                ('type', models.CharField(max_length=32, verbose_name='评论来源类型')),
                ('parent_comment_id', models.IntegerField(default=0, verbose_name='父评论ID')),
                ('user_id', models.IntegerField(verbose_name='发表用户ID')),
                ('floor_comment_id', models.IntegerField(blank=True, null=True, verbose_name='楼层评论ID')),
                ('parent_user_id', models.IntegerField(blank=True, null=True, verbose_name='父发表用户名ID')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comment_content', models.CharField(max_length=1024, verbose_name='评论内容')),
                ('comment_info', models.CharField(blank=True, max_length=256, null=True, verbose_name='评论额外信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文章评论表',
                'verbose_name_plural': '文章评论表',
                'db_table': 'comment',
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['source'], name='idx_comment_source'),
        ),
    ]
