# Generated by Django 4.1.5 on 2023-08-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
        ),
    ]
