# Generated by Django 4.1.5 on 2023-07-21 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appone', '0002_comment_comment_idx_comment_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32, verbose_name='资源类型')),
                ('path', models.CharField(max_length=256, verbose_name='资源路径')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='资源内容的大小，单位：字节')),
                ('mime_type', models.CharField(blank=True, max_length=256, null=True, verbose_name='资源的MIME类型')),
                ('status', models.BooleanField(default=True, verbose_name='是否启用[0:否，1:是]')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '资源信息',
                'verbose_name_plural': '资源信息',
                'db_table': 'resource',
            },
        ),
    ]
